name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'